CREATE SCHEMA `tecnoparque` ; 

create table `tecnoparque`.`carga_jira` (
`id_jira` INT NOT NULL,  
`key` VARCHAR(45) NULL,
`issue_type` VARCHAR(45) NULL,
`status` VARCHAR(45) NULL,
`priority` VARCHAR(45) NULL,
`summary` VARCHAR(45) NULL,
`description` VARCHAR(45) NULL,
`reporter` VARCHAR(45) NULL,
`assignee` VARCHAR(45) NULL,
`created` DATETIME NULL,
`due_Date` DATETIME NULL,
`updated` DATETIME NULL,
`resolved` DATETIME NULL,
`labels` VARCHAR(45) NULL, 
`fecha_carga` DATETIME NULL,
`hora_carga` TIME NULL,
PRIMARY KEY (`id_jira`));

create table `tecnoparque`.`h_carga_jira` (
`id_jira` INT NULL,  
`key` VARCHAR(45) NULL,
`issue_type` VARCHAR(45) NULL,
`status` VARCHAR(45) NULL,
`priority` VARCHAR(45) NULL,
`summary` VARCHAR(45) NULL,
`description` VARCHAR(45) NULL,
`reporter` VARCHAR(45) NULL,
`assignee` VARCHAR(45) NULL,
`created` DATETIME NULL,
`due_Date` DATETIME NULL,
`updated` DATETIME NULL,
`resolved` DATETIME NULL,
`labels` VARCHAR(45) NULL,   
`fecha_carga` DATETIME NULL,
`hora_carga` TIME NULL,
PRIMARY KEY (`id_jira`));


CREATE TABLE `tecnoparque`.`actividad_jira`(
`c_status`                                 SMALLINT NOT NULL,   
`paso`                                     DATETIME   NULL,         
`key_`                                     VARCHAR(45) NULL,    
`issue_type`                               VARCHAR(45) NULL,    
`status`                                   VARCHAR(45) NULL,    
`priority`                                 VARCHAR(45) NULL,    
`summary`                                  VARCHAR(45) NULL,    
`description`                              VARCHAR(45) NULL,    
`reporter`                                 VARCHAR(45) NULL,    
`assignee`                                 VARCHAR(45) NULL,    
`fecha_del_dia`                            DATETIME   NULL,     
`fecha_creacion_created`                   DATETIME   NULL,     
`fecha_inicio`                             DATETIME   NULL,     
`dias_transcurridos_al_dia`                INTEGER   NULL,      
`fecha_prometida__vs_ns`                   DATETIME   NULL,     
`fecha_prometida__due_date`                DATETIME   NULL,     
`dias_ret_vs_f_prom_ns`                    INTEGER   NULL,      
`dias_ret_vs_f_prom_due_date`              INTEGER   NULL,      
`dias_brecha`                              INTEGER   NULL,      
`fecha_cierre_resolved`                    DATETIME   NULL,         
`cumplio_ns`                               SMALLINT  NULL,      
`cumplio_fp`                               SMALLINT  NULL,      
`dias_efectivos`                           DATETIME   NULL,         
`labels`                                   VARCHAR(45)   NULL,  
`nivel_servicio`                           SMALLINT   NULL,     
`fecha_reincidencia_1`                     DATETIME   NULL,         
`fecha_reincidencia_2`                     DATETIME   NULL,         
`fecha_reincidencia_3`                     DATETIME   NULL,         
`fecha_reincidencia_4`                     DATETIME   NULL,         
`sow3`                                     SMALLINT   NULL, 
`fecha_autorizacion`                       DATETIME   NULL,
`dias_autorizacion`                        SMALLINT   NULL,
`raiz_wa`                                  VARCHAR(45) NULL,
PRIMARY KEY (KEY_));



