INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-807','Enhancement','Open','Medium','En el formato de la posici?n de TAS debe de ordenar la Columna de "Emisora" de una forma mas ordenada','Al ver una posici?n el sistema TAS deberia de ordenar la columna "Posici?n" primero por mercado (esto ya lo hace) y despues la columna "Emisora" por orden Alfabetico ya que se veria mas ordenada la Posici?n al igual que Fiable lo muestra.  ','Ana Mayte Topete','Ana Mayte Topete','2014/10/22 12:05',NULL,'2015/02/17 18:42',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-31','Enhancement','Open','Medium','Comisiones e Ingresos','Cobro de comisiones a contratos e ingresos generados por promotor.  Corresponde al ID TAS 36 de Brechas e Interfaces Bx+','I?igo Aguilar','Sergio Rangel','2013/10/19 15:19',NULL,'2015/02/17 18:42',NULL,'Broker, FSP1307, Gap, Licencia',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-30','Enhancement','In Progress','Medium','Notificaciones via e-mail de Operaciones de Derivados y Sobregiros.','Especificaci?n para la notificaci?n via e-mail de la realizaci?n de operaciones de Derivados as? como en los sobregiros de l?neas de cr?dito para operaciones de Derivados y Mercado de Dinero.  Corresponde al ID 10 y 16 de Brechas e Interfaces','Alejandra Ivonne Gonz?lez Venancio','Francisco Morales L?pez','2013/10/18 18:41',NULL,'2015/02/17 18:40',NULL,'FSP578, FSP579, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-93','Enhancement','In Progress','Medium','Administrar t?tulos y efectivo por inclumplimiento.','Administrar t?tulos y efectivo cuando se incumpla la entrega o recepci?n de los valores.  Corresponde al ID 116 de Brechas e Interfaces.','Agustin Gutierrez','Sergio Rangel','2014/01/20 13:46',NULL,'2015/02/17 18:40',NULL,'Broker, Gap, Licencia, TAS-CM',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-708','Enhancement','In Progress','Medium','En la revisi?n de Perfiles se identifico que No existe en TAS (Factor de ISR en la Consulta de Precios)','En la revisi?n de Perfiles se identifico que No existe en TAS   No se tiene evidencia del incidente','Juan Carlos Fern?ndez','Francisco Morales L?pez','2014/09/29 19:37','2015/02/17','2015/02/17 18:40',NULL,'Broker, FSP1307, Gap, PruebasDX, ciclo3',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-574','Enhancement','Delivered','Medium','Eliminar ordenes de fondos programadas','TAS no permite cancelar compras o ventas de fondos previamente programadas o formadas, solo se puede cancelar operaciones el d?a que corresponde reportar a la operadora y previo al cierre.','Juan Carlos Fern?ndez','Juan Carlos Fern?ndez','2014/09/11 17:00',NULL,'2015/02/17 18:32',NULL,'Broker, FSP1307, Gap, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-26','Enhancement','Delivered','Medium','Funcionalidad Hos to Host','Se anexa documento de especificaci?n para su revisi?n.  Funcionalidad Host to Host.  Corresponden a los ID 137 y 163 del Inventario de Interfaces proporcionado por Bx+.','Agustin Gutierrez','Antonio Laija Olmedo','2013/10/17 13:36',NULL,'2015/02/17 18:31',NULL,'FSP578, FSP579, PruebasD4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-316','Enhancement','Delivered','Medium','Realizar Interfaz Solutrust Fideicomisos (Operaciones)','Realizar interfaz','Ana hernandez','Ana hernandez','2014/07/03 14:27',NULL,'2015/02/17 18:30',NULL,'Broker, FSP1307, Gap',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-90','Enhancement','Failed Test','Medium','Realizar Carga de Boletin Electronico','Realizar la carga de bolet?n electr?nica para generar la aplicaci?n de ejercicios de derecho de manera autom?tica.  Corresponde al ID 31 de Brechas e Interfaces.','Agustin Gutierrez','Agustin Gutierrez','2014/01/20 12:03','2015/02/17','2015/02/17 18:30',NULL,'FSP1307, PruebasD4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-88','Enhancement','Failed Test','Medium','Repore Global de Utilidades.','Reporte global de utilidades por promotor, trader, centro de costos (corvalin)  Corresponde al ID 25 de Brechas e Interfaces.','Jocelyn Vazquez','Sergio Rangel','2014/01/20 11:59',NULL,'2015/02/17 18:29',NULL,'Broker, FSP580, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-847','Enhancement','Failed Test','Medium','Brecha Contabilidad: P?liza de Provisi?n de Comisiones pos Distribuci?n de Fondos de Inversi?n)','Brecha Contabilidad: P?liza de Provisi?n de Comisiones pos Distribuci?n de Fondos de Inversi?n)   Se sube especificaci?n','Jocelyn Vazquez','Arturo Saldivar','2014/10/28 19:43',NULL,'2015/02/17 18:28',NULL,'Broker, Ciclo4, Gap, OutScope',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-290','Enhancement','Failed Test','Medium','El archivo en excel de SI para Compass Group s?lo debe mostrar ordenes registradas a una fecha','El archivo en excel de Sociedades de Inversi?n para Compass Group est? mostrando tanto ordenes que se registraron el d?a en el que se genera dicho archivo, como aquellas que liquidan y que se operaron con anterioridad. Lo correcto es que solamente despliegue las ordenes registradas en el d?a. Adicionalmente, en el campo de contrato debe de aparecer el contrato 1459, que es el n?mero de contrato que tiene el distribuidor registrado en el sistema SisDisi.  ','Juan Carlos Fern?ndez','Arturo Saldivar','2014/06/25 17:18','2015/02/13','2015/02/17 18:28',NULL,'Broker, FSP1307, Gap',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-891','Enhancement','In Progress','Medium','Desarrollar la Convalidaci?n de la Asignaci?n de precios de t?tulos Moneda Nacional','Se requiere el desarrollo de la Convalidaci?n de acuerdo a los requerimientos mensuales de Banco de M?xico.   El layout se conforma de la columna A a la H de la pesta?a "AP1_Tenencia A_Precio MXN0714"  ','Veronica Angeles','Gerardo Tenopala','2014/11/06 14:27','2015/02/25','2015/02/17 18:01',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1219','Enhancement','In Progress','High','Realizar carga de operaciones de colocaciones primarias','Se requiere recibir del modulo de colocaciones primarias las asignaciones que este sistema realiza. En TAS se pueden grabar como operaciones de compra - venta de mercado de dinero, pero se deben de marcar en algun campo como colocacion primaria, ya que en el estado de cuenta y en la consulta de movtos se debe de identificar de esta manera.   Para mercado de capitales, hay que solicitarle la modificaci?n a la interface actual, para que en alg?n campo nos indique que la operaci?n recibida es de colocaci?n primaria. El objetivo al igual que en MD es que se identifiquen como colocaci?n primaria.','Gerardo Gomez','Jacqueline Barradas','2015/02/04 11:57',NULL,'2015/02/17 17:59',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-578','Enhancement','Delivered','Medium','Realizar asignaci?n de fondos en cuanto se tenga precio','Realizar la asignaci?n de fondos en el cierre del dia en que se conozca el precio. Es decir, el sistema no debe de esperar hasta un d?a antes para realizar la asignaci?n y liquidaci?n de operaciones.','Juan Carlos Fern?ndez','Juan Carlos Fern?ndez','2014/09/17 10:23',NULL,'2015/02/17 17:26',NULL,'Broker, FSP1307, Gap, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-853','Enhancement','Delivered','Medium','Solicitud de Cambio para la Interfaz Investor-Zeus','Se anexa documento de Solicitud de Cambio para el archivo de posici?n del m?dulo Zeus','Juan Carlos Fern?ndez','Margarita Arellano','2014/10/30 12:18','2015/02/12','2015/02/17 16:44',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1304','Enhancement','In Progress','High','Realizar interfaz de colocaciones primarias de capitales','Se requiere que en la interfaz de capitales se indentifique colocacion primaria','Gerardo Gomez','Jacqueline Barradas','2015/02/16 13:40',NULL,'2015/02/17 15:04',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-329','Enhancement','Delivered','Medium','Reporte de Custodias por Sucursal','REPORTE DE CUSTODIAS POR SUCURSAL (Agregar Sucursal) Al reporte de custodias por sucursal se requiere agrupaci?n por sucursal.','Ana hernandez','Ana hernandez','2014/07/09 11:50','2015/02/16','2015/02/17 15:01',NULL,'Broker, FSP1307, Gap, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1160','Enhancement','Investigating','High','Relizar adecuaciones al estado de cuenta','Relizar la adicion de los siguintes conceptos:  A continuaci?n los conceptos que no se ten?an contemplados en el formato original.   /BanderasDeProcesamiento  perfilinversion  serviciosinversion   /Comprobante  Lugarexpedicion  Numctapago  Foliofiscalorig  Seriefoliofiscalorig  Fechafoliofiscalorig  Montofoliofiscalorig  metodoDePago  tipoDeComprobante   /Emisor  /reg?menes  regimen   /Conceptos  /Adicionales  importeConImpuestos  impuestos  porcentaje  encabezado  SubTotal  SubTotalImpuestos  SubTotalConImpuestos  SubTotalPorcentaje   /Impuestos  /Retenciones  /Retencion  Importe (cambio la etiqueta valor anterior importeImpuesto)   /Traslados  /Traslado  Importe (cambio la etiqueta, valor anterior importeImpuesto)   /Totales  LeyendaImpuestoA?o  LeyendaImpuestoMes  leyendaInforme   /ECB  /InformeResultados  /Linea  valuacionCorteAnual   /InformeResultadosAdicional  /Linea  Perfil  valuacionCorte  valuacionCorteAnual   /DetallePosicion  Sumaporc  /Posicion  Tipoval  dias/diasporvencer (solo cambio la etiqueta)  valorMerc/valor (solo cambio la etiqueta)  fechaVenc/fechavencimiento (solo cambio la etiqueta)  premio  plusminusvalia  valorAdquisicion  valorCosto  premio   /Movimientos  /Movimiento  tVal/ tipoval (solo cambio la etiqueta)   /ManejoCuenta  Aplica   /PrincipalesIndicadores  /l?nea  descripcion  valuacionCorte  valuacionCorteAnual  ','Margarita Arellano','Margarita Arellano','2015/01/23 13:20','2015/02/19','2015/02/17 14:48',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-33','Enhancement','In Progress','Medium','ERAS GANANCIA Y GENERACI?N POR TENENCIA PARA CASA DE BOLSA Y PROMOCI?N DE SOCIEDADES DE INVERSI?N Y PROVISI?N CONTABLE','El Sistema TAS genere un reporte de Tenencia de las Sociedades de Inversi?n que distribuye la Casa de Bolsa, donde calcule por un factor la ganancia que recibe la Casa de Bolsa de la Operadora de Fondos y otro factor que aplique a los Promotores para su generaci?n, tanto la ganancia de la Casa de Bolsa como la generaci?n del Promotor el Sistema TAS calcule sus provisiones contables (N?mero de Acciones X Precio de Mercado X Factor).','Ana hernandez','Arturo Saldivar','2013/10/22 15:25',NULL,'2015/02/17 14:38',NULL,'Broker, Gap, Licencia, PruebasD2, TAS-Funds',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-42','Enhancement','Delivered','Medium','ERAS CENTROS DE COSTOS','Que el Sistema TAS permita a la Instituci?n ingresar los Centros de Costos que maneja su Sistema Contable, permitiendo al Usuario asociar estos Centros de Costos a Contratos, Promotores y Negociadores, cuando se genere la contabilidad de Mercado de Capitales, Mercado de Dinero, Derivados y Sociedades de Inversi?n contenga estos Centros de Costos las cuentas Contables asociadas.','Ana hernandez','Ana hernandez','2013/10/30 17:26','2015/02/12','2015/02/17 14:35',NULL,'Broker, FSP580, Gap, PruebasD3, SCPC, TAS-Gral',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-515','Enhancement','Investigating','Medium','Cambios a la Interfaz de Clientes por Bajas y Manejo de Nombre-Apellidos','Se solicitan los siguientes cambios en la interfaz de Clientes:   1. Recibir el Nombre del Cliente en los casos de personas f?sicas, separado en tres variables distintas para evitar que la interfaz tenga que diferenciar nombre y apellidos.  Adem?s se necesita que se permitan los valores vac?os o nulos en los apellidos, incluyendo los correspondientes a co-titulares y/o beneficiarios.   2. Manejo de Bajas y Modificaciones para datos adicionales del cliente  - Direcciones  - Co-titulares  - Beneficiarios   Se deja a continuaci?n el requerimiento de Jesus Villase?or descrito en el ticket BXMPRJ-434:   - 1) Se envia alta de cliente solo con el campo NOMBRE (completo) y de alguna forma TAS esta cargando los datos de Apellido Paterno Materno y Nombre . Se observa que se estan asignado los paternos como maternos y viceversa , tambien que aunque en la mayoria de los casos el corte es correcto esto no pasa siempre. SE SOLICITA CONTEMPLAR EL CAMBIO a peticion separada NOMBRES , APELLIDO1 , APELLIDO2 y aceptar que cualquiera de los apellidos puede venir en blanco. (TAMBIEN EN COTITULARES, BENEFICIARIOS).   - 2) En la Interface no se contemplan BAJAS de ningun dato, pero si existen , por ejemplo del CONTRATO y de algunos datos como DIRECCIONES , BENEFICIARIOS , COTITULARES , etc .. como se pretende que se maneje esto ...  ','Cesar Guzm?n','Christian Ramirez','2014/08/25 13:32',NULL,'2015/02/17 14:25',NULL,'FSP1307, PruebasD2',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1250','Enhancement','Open','Medium','Cierre de fondos cuando caja este cerrada','Se requiere que se permita hacer el cierre de fondos cuando la caja se encuentre cerrada','Javier Hern?ndez','Gabriela Cedillo','2015/02/07 1:08','2015/02/25','2015/02/17 13:48',NULL,'SCPC',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1158','Enhancement','Failed Test','High','SOLICITUD DE AUTORIZACION INNECESARIA','Al momento de revisar si existen ?rdenes pendientes por autorizar nos encontramos con 3, de las cuales solo una requiere autorizaci?n, aparentemente ya que TAS no cuenta son mensajes informativos del por que se requiere autorizaci?n.   Se adjunta evidencia.','Martin Cruz','Carmen M?ndez','2015/01/22 22:19','2015/02/19','2015/02/17 11:25',NULL,'CICLO4, SCPC',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1207','Enhancement','Open','Medium','Reporte Detallada llamadas de Margen DGARW007','El d?a 30 de enero de 2015 en una reuni?n con Juan Carlos Jaques, Elisa Paz, Margarita Arellano y Gerardo G?mez, se determin? que Fiable llevar? la administraci?n de las garant?as por cauci?n.Por lo anterior se solicita que las garant?as por causi?n ya no se presenten en este reporte.   Adicional para este reporte se solicita la siguiente informaci?n:   1. La columna Aforo viene vac?a, Mesa de controles necesita conocer el aforo para asegurar el c?lculo, el dato se obtiene en el archivo de Indeval.   2. El reporte se requiere complementar con los campos:  a. Tipo Valor.  b. Calificaci?n/Bursatilidad.  c. Monto a Garantizar.   Favor de atender el requerimiento  ','Cesar Guzm?n','Carmen M?ndez','2015/02/03 15:12','2015/02/23','2015/02/17 11:24',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1159','Enhancement','In Progress','Medium','Amortizaciones por Importe y por T?tulos.','Se necesita completar la funcionalidad para realizar las amortizaciones de MC por Importe y por T?tulos.  Haciendo las afectaciones correspondientes para que se generen las liquidaciones y/o movimientos de vencimiento.   Este JIRA es un complemento del JIRA BXMPRJ-688.','Carmen M?ndez','Carmen M?ndez','2011:07/23/Jan AM','2015/02/27','2015/02/17 11:23',NULL,'SCPC',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-568','Bug','In Progress','Medium','Corregir observaciones en interfaz Signar','1. LA ACCI?N DE PINFRA NO TRAE LA MONEDA, COLUMNA L  2. ACCIONES DE POP NO SE ASIGNARON A CLIENTES Y DEBER?A QUEDAR EN PORTAFOLIO DE SOBRANTES DE LA POSICION PROPIA Y NO APARECEN EN EL LAYOUT."  3.VENTAS EN REPORTO LA COLUMNA DE TASA CUP?N EST? EN CERO LO CUAL ES INCORRECTO  4.VENTAS EN REPORTO NO EST? IDENTIFICADA EN LA COLUMNA LA POSICI?N DE DISPONIBLE PARA LA VENTA  5.EN LA COLUMNA DE TASA REPORTO VIENE INFORMACI?N CUANDO DEBER?A ESTAR EN CERO AL SER POSICI?N EN DIRECTO  6.DIRECTO NO EST? IDENTIFICADA LA POSICI?N DE LOS PORTAFOLIOS  7. VENTAS EN REPORTO LA COLUMNA DE TASA DE REPORTO ESTA EN CERO, LO CUAL ES INCORRECTO.  8. VENTAS EN REPORTO PARA LOS BANOB, BMAS, SHF0001 NO TRAE TIPO VALOR, LA PRIMER LETRA DE LA EMISORA LO SUSTITUYE.  9. VENTAS EN REPORTO BANOB10 Y BANOB 13 NO EST?N EN MATRIZ.  10. VENTAS EN REPORTO BPA182 180104 CORRESPONDE AL PORTAFOLIO DISPONIBLE PARA LA VENTA Y NO ESTA CLASIFICADO."  11. DIRECTO COLUMNA TASA REPORTO TRAE INFORMACI?N CUANDO DEBE ESTAR EN CERO.  12. DIRECTO PAGARE NO COINCIDE EL MONTO CON MATRIZ."   ','Alejandra Ivonne Gonz?lez Venancio','German Gomez','2014/09/11 10:17','2015/02/27','2015/02/17 18:36',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-744','Bug','In Progress','Medium','Algunas interfaces del cierre de caja no se generan','Se prob? la soluci?n del ticket BXMPRJ-412, la cual a traves de la funci?n "Interfaces del Cierre de Caja JINTW100" se generan cada una de las interface teniendo como resultado lo siguiente:   Interface DWH: manda mensaje de error  Interface SIPREV: se genera correctamente  Interface Investor Movimientos: se genera correctamente  Interface Investor Vauaci?n: se genera correctamente  Interface Zeus Posicion: se genera correctamente  Cobro de Cuota de Admon: no se genera ning?n archivo  Generaci?n Ingresos x Prom: no se gener ning?n archivo   Se adjunta evidencia de la prueba, as? como los archivos generados.','Antonio Laija Olmedo','Edgar Richter','2014/10/08 10:37','2015/02/19','2015/02/17 18:35',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-340','Bug','In Progress','Medium','Reporte Tenencia Fondos','El Reporte de Tenencias de Fondos presenta las siguientes inconsistencias:   1. Cuando se genera por Emisora, la columna Acciones Fondos no est? tomando el total de t?tulos por emisora-serie. Cuando se genera por Promotor y Emisora, si toma el total de t?tulos para la mayor?a de las emisoras serie.   2. Se est?n duplicando registros   3. Se est?n mostrando registros desfasados   Se anexa evidencia.   ','Juan Carlos Fern?ndez','Arturo Saldivar','2014/07/10 16:31',NULL,'2015/02/17 18:35',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-386','Bug','Failed Test','Medium','En ejercicio de derechos de dividendo en efectivo el sistema no retiene el factor de ISR capturado.','En ejercicio de derechos de dividendo en efectivo el sistema no retiene el factor de ISR capturado.   Se adjuntan 2 documentos con la evidencia.','Agustin Gutierrez','Sergio Rangel','2014/07/29 12:45','15/01/08','2015/02/17 18:30',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-103','Bug','Failed Test','Medium','Errores en Interfaz SIPREV (Archivos Prueba)','Evidencia de Archivos prueba generados por TAS para Interfaz SIPREV.','Christian Gonz?lez Flores','Margarita Arellano','2014/02/18 13:00','2015/02/16','2015/02/17 18:29',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1020','Bug','In Progress','High','Error Interfaz ECC p?liza diaria SAP (SI)','Se intent? correr el proceso de Interfaz ECC, para Soc.Inv.(documentos preliminares de carga), sin embargo no se pudo realizar por falta de Centros de Costos y Ordenes Internas, las cuales ya hab?a configurado el proveedor de TAS, sin esta informaci?n no se puede contabilizar.  Se anexa evidencia.  ','Jocelyn Vazquez','Gerardo Tenopala','2014/12/09 17:46','2015/02/20','2015/02/17 18:02',NULL,'PruebasD3',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-384','Bug','Failed Test','High','No se puede aplicar un derecho de suscripci?n','No se puede aplicar un derecho de suscripci?n. regresando a la pantalla original como para aplicar; y dejando a los participantes en el derecho, como NO autorizados.   Se incluye como evidencia las pruebas realizadas.','Agustin Gutierrez','Agustin Gutierrez','2014/07/28 13:34','2015/02/17','2015/02/17 15:06',NULL,'Detiene, PruebasD4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-889','Bug','Delivered','Medium','Desarrollar la Convalidaci?n de la Clasificaci?n de T?tulos Moneda Nacional Operaciones Vigentes','Se requiere el desarrollo de la Convalidaci?n de acuerdo a los requerimientos mensuales de Banco de M?xico.   El layout se conforma de la columna B a la I de la pesta?a "CL3 Cl_Cont_OpVig_MXN0714"  ','Veronica Angeles','Erick V?zquez','2014/11/06 14:21',NULL,'2015/02/17 13:50',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-894','Bug','Delivered','Medium','Desarrollar la Convalidaci?n de la Asignaci?n de precios de t?tulos M.N. Operaciones Vigentes','Se requiere el desarrollo de la Convalidaci?n de acuerdo a los requerimientos mensuales de Banco de M?xico.   El layout se conforma de la columna B a la I de la pesta?a "AP3_OpVig A_PrecioMXN0714"','Veronica Angeles','Erick V?zquez','2014/11/06 14:35',NULL,'2015/02/17 13:49',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1260','Bug','In Progress','High','Operaciones faltantes en CVT, Reportos y Transferencia','Iv?n,   De la revisi?n llevada a cabo para las operaciones de CVT y Reportos del d?a 29/07/2014, as? como Transferencias del 30/07/2014 encontr? algunas operaciones que se generaron en el reporte diario de operaciones pero no as? en sus respectivos reportes regulatorios. Anexo papeles de trabajo en los cuales se encuentran integrados el reporte diario de operaciones as? como el regulatorio correspondiente, favor de apoyarme con la aclaraci?n o la inclusion de las operaciones en cuestion.  Reportos TR CVT Reportos  30/07/2014 30/07/2014 29/07/2014 29/07/2014  104173 104234 104039 103773  104169 104231 104038  104173 104207 103952  104169 104044  104125  104174    Gracias','Erick V?zquez','Carmen M?ndez','2015/02/09 17:47','2015/02/20','2015/02/17 11:24',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1283','Bug','Delivered','Medium','Error en en la generaci?n del reporte de derivados para la validaci?n de contabilidad','Al ejecutar el d?a de hoy el el reporte de Derivados, para revisar el d?a 31.07.14, no se genera y el sistema env?a el mensaje que se adjunta en el archivo','Irma Aguilar','Jocelyn Vazquez','2015/02/12 11:44',NULL,'2015/02/17 10:46',NULL,'',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1273','Question','Investigating','High','Se tienen 11342 registros por concepto de Cobro por Administraci?n en el Reporte de Flujo Cambios','El 09 de Febrero, Prueba d?a 4 se valida la posici?n del Reporte de Flujo Cambios la cual debe de estar en blanco al inicio de la operaci?n. Al momento de generar el Reporte este se tardo en mostrar la informaci?n porque tenia 11342 movimientos que se cargaron por el concepto Cobro por Administraci?n. Se anexa evidencia','Beatriz P?rez','Ivan Torres','2015/02/10 19:58',NULL,'2015/02/16 19:32',NULL,'CICLO4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-1214','Question','Client Response Provided','High','Estado de cuenta','toda la informcion que presenta el estado de cuenta esta en ceros','Azucena Gudi?o','Gerardo Gomez','2015/02/03 19:10','2015/02/24','2015/02/17 11:11',NULL,'PruebasD4, ciclo4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-833','Question','In Progress','Medium','Layout Signar FECHAS VALOR','LAS COMPRAS Y VENTAS FECHA VALOR NO CUADRAN EN TAS CON RESPECTO A PRODUCCION','Javier Hern?ndez','German Gomez','2014/10/23 19:33','2015/02/27','2015/02/16 19:31',NULL,'PruebasD4, ciclo4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-832','Question','In Progress','Medium','layout SIGNAR cambios','la posicion de las divisas que son mismo dia en el layout de Signar estan regsitradas como 24 horas.','Javier Hern?ndez','German Gomez','2014/10/23 19:29','2015/02/27','2015/02/16 19:31',NULL,'CICLO4, PruebasD4',CURDATE(),curtime())

INSERT INTO carga_jira (id_jira,key_,issue_type,status_,priority,summary,description,reporter,assignee,created,due_Date,updated,resolved,labels,fecha_carga,hora_carga )values (0,'BXMPRJ-231','Question','Client Response Provided','Medium','SI FALTA ALG?N PRECIO DE LOS FONDOS QUE DISTRIBUYE CB BX+, SOLICITAN QUE NO ABRA EL FONDO EL SIGUIENTE D?A H?BIL HASTA QUE EXISTA EL PRECIO','Solicita BX* que en caso de no recibir un precio de los fondos que hoy distrubuye la Casa de Bolsa, el Sistema TAS no permita abrir el fondo en cuesti?n hasta que no se se suba el precio al sistema, generalmente esta situaci?n se presenta frecuentemente y necesitan que consideremos esta situaci?n en el cierre y aperura del m?dulo de FONDOS, se les informo que actualmente el Sistema TAS no permite el cierre del m?dulo si no cargan los precios de los fondos que hoy distribuyen.   Les comparto los correos involucrados con el tema,   Quedo pendiente.   Saludos,  Jos? Arturo Saldivar  FSS & TAS   __________________________________________________________________________________________________________________________________  De: Margarita Arellano Reyes [mailto:marellano@vepormas.com.mx]  Asunto: RV: REENVIO PRECIOS XLS 28-05-14 INCURSI?N PRECIO SAURORT   Arturo,   Me puedes indicar que har?amos en TAS , para este escenario en el cual la operadora de sociedades de inversi?n no reporto el precio en el d?a en que se ten?a que cerrar una operaci?n de fondos, como ves en el texto , se report? al d?a siguiente   Quedo pendiente  ___________________________________________________________________________________________________________________________________  De: Juan Carlos Fernandez Hernandez [mailto:jfernandez@vepormas.com.mx]  Enviado el: Thursday, 29 de May de 2014 11:29 a.m.  Para: Margarita Arellano Reyes; Jesus Villase?or Cazares; arodriguez@vepormas.com.mx  CC:  Valores Ve por Mas ; agutierrez@vepormas.com.mx; mmendeza@vepormas.com.mx; rhernandez@vepormas.com.mx; masanchez@vepormas.com.mx; ahernandez@vepormas.com.mx  Asunto: RV: REENVIO PRECIOS XLS 28-05-14 INCURSI?N PRECIO SAURORT   ESTIMADOS, ACABO DE MODIFICAR EL PRECIO DEL SAURORT, YA QUE EL QUE LLEGO AYER POR LA TARDE NOCHE, EL PRECIO ESTABA EN CEROS, ME ACABAN DE ENV?AR EL PRECIO CORRECTO (1.015157).   AYER HUBO COMPRA PARA EL CLIENTE 518192, POR LO QUE HAY QUE REPORCESAR PARA QUE ESTE FONDO SE CIERRE Y SE ASIGE DE FORMA CORRECTA.      ','Juan Carlos Fern?ndez','Juan Carlos Fern?ndez','2014/06/04 0:43',NULL,'2015/02/17 17:18',NULL,'Gap, PruebasD3',CURDATE(),curtime())
